canals/pipeline/connections.py
canals/pipeline/pipeline.py
canals/pipeline/sockets.py
canals/pipeline/validation.py
test/pipelines/unit/test_validation_pipeline_io.py

The current field `taken_by` is confusing as it's not clear whether it refers to the receving or sender node.
We change it to `sender` so that's it's clear what it refers to.

Change InputSocket taken_by field to sender

---

canals/component/component.py
canals/component/input_output.py
canals/draw/draw.py
canals/pipeline/pipeline.py
canals/pipeline/sockets.py
canals/pipeline/validation.py
test/component/test_component.py
test/pipelines/integration/test_complex_pipeline.py
test/pipelines/integration/test_looping_and_merge_pipeline.py
test/pipelines/integration/test_looping_pipeline.py
test/pipelines/integration/test_variable_decision_and_merge_pipeline.py
test/pipelines/integration/test_variable_merging_pipeline.py
test/pipelines/unit/test_input_sockets.py
test/pipelines/unit/test_validation_pipeline_io.py
test/sample_components/test_merge_loop.py
test/sample_components/test_sum.py

We're removing `variadics` inputs as they're not strictly necessary. Components that need variable inputs will be able to define them when initializing the component.
Variadics had also the benefit of running even if not all inputs where received, that made possible to have cycles in pipelines. This is why we had to skip some tests.
In a following PR we'll add support for components running with partial inputs, that will make it possible to have cycles in pipelines again.

Remove variadics

---

canals/component/component.py
canals/pipeline/pipeline.py
test/pipelines/integration/test_complex_pipeline.py
test/pipelines/integration/test_double_loop_pipeline.py
test/pipelines/integration/test_looping_pipeline.py
test/pipelines/integration/test_variable_decision_and_merge_pipeline.py
test/sample_components/test_merge_loop.py
test/sample_components/test_sum.py

Component's input dataclasses that have `Optional` fields are now treated as partials.
If those `Optional` fields are skipped and never received the component will run anyway, it will first wait to be sure that those inputs are actually skipped and will never be received.
This enables us to have cycles in Pipeline.
Closes #27

Handle components with partial input

---

canals/component/component.py
test/component/test_component.py

`component` is now an instance of the `_Component` class.
This makes it easier set `component.input` and `component.output` property, this also enables autocompletion.
I also added a registry to keep track of all classes marked with `@component`.
Closes #30

Make component decorator a class

---

canals/errors.py
canals/pipeline/__init__.py
canals/pipeline/save_load.py
test/test_save_load.py

Remove the `dependencies` section in marshaled Pipelines to leverage component registry.
Closes #31

Remove dependencies section in marshaled pipelines

---

canals/component/component.py
test/component/test_component.py

Fix a bug that was preventing components from having additional Python properties other than `input` and `output`.

fix: fix logic operator and add tests

---

canals/__init__.py
test/_helpers.py
test/component/test_component.py
test/pipelines/unit/test_connections.py
test/pipelines/unit/test_draw.py
test/pipelines/unit/test_input_sockets.py
test/pipelines/unit/test_output_sockets.py
test/pipelines/unit/test_pipeline.py
test/pipelines/unit/test_validation_pipeline_io.py
test/sample_components/test_accumulate.py
test/sample_components/test_add_value.py
test/sample_components/test_concatenate.py
test/sample_components/test_double.py
test/sample_components/test_greet.py
test/sample_components/test_merge_loop.py
test/sample_components/test_parity.py
test/sample_components/test_remainder.py
test/sample_components/test_repeat.py
test/sample_components/test_subtract.py
test/sample_components/test_sum.py
test/sample_components/test_threshold.py
test/test_save_load.py

Simplify imports of public interface.
Previous:
```
from canals.component import component
from canals.pipeline import Pipeline
```
Now:
```
from canals import component, Pipeline
```

Simplify public interface imports

---

canals/pipeline/connections.py
canals/pipeline/draw/__init__.py
canals/pipeline/draw/draw.py
canals/pipeline/draw/graphviz.py
canals/pipeline/draw/mermaid.py
canals/pipeline/pipeline.py
canals/pipeline/sockets.py
canals/pipeline/validation.py
test/conftest.py
test/pipelines/unit/test_connections.py
test/pipelines/unit/test_draw.py
test/pipelines/unit/test_input_sockets.py
test/pipelines/unit/test_output_sockets.py
test/pipelines/unit/test_validation_pipeline_io.py

`draw` module has been moved in `pipeline` module and all its methods defined as private.
The only public API to draw a pipeline will be `Pipeline.draw()` as it currently is.
This PR also makes all the validation, connections and sockets handling methods private as they must not be part of the public interface.
Depends on #53

Move draw in pipeline module and clearly define public interface

---

pyproject.toml

With this change we include only `.py` files found in the `canals` folder.
Previously we were including most files in the project excluding those in `.gitignore` has Hatch respects that by default.

Include only required files in built wheel

---

canals/component/component.py
test/component/test_component.py
test/sample_components/test_sum.py

Verifying I/O types at run time is not a good practice as it's extremely hard and error prone since Python is a dynamic language.
Comparing Component's output is close to impossible without limiting extremely the possible output types. Since it's good enough to have validation in Pipeline when connecting Components we decided to remove the run time checks.

Remove Component's I/O type checks at run time

---

canals/component/component.py
canals/errors.py
test/component/test_component.py

Add `from_dict` and `to_dict` to `Component` interface.
All classes decorated with `@components` will have a default implementation added.
Given a `MyComponent` class that accepts a `value` parameter in `__init__` `to_dict()` will create a dictionary similar to this:
```
{
"hash": <id_of_the_instance>,
"type": "MyComponent",
"init_parameters": { "value": 100 },
}
```
`MyComponent.from_dict()` will instead return a new instance of `MyComponent` given the above dictionary.
Trying to call `OtherComponent.from_dict()` using the above dictionary will fail.

Add component `from_dict` and `to_dict` methods

---

canals/pipeline/pipeline.py
canals/testing/test_component.py
test/pipelines/unit/test_pipeline.py

Depends on #68.
Add `Pipeline.from_dict()` and `Pipeline.to_dict()` methods.
`Pipeline.to_dict()` will create a similar dictionary:
```
{
"metadata": {"test": "test"},
"max_loops_allowed": 100,
"components": {
"add_two": {
"type": "AddFixedValue",
"hash": 123,
"init_parameters": {"add": 2},
},
"add_default": {
"type": "AddFixedValue",
"hash": 456,
"init_parameters": {},
},
"double": {
"type": "Double",
"hash": 789,
"init_parameters": {},
},
},
"connections": [
{"sender": "add_two.result", "receiver": "double.value"},
{"sender": "double.value", "receiver": "add_default.value"},
],
}
```
Each component dictionary will be created using that component instance `to_dict()` method.
`Pipeline.from_dict()` will take the above dictionary and return a new `Pipeline` instance.
We can also pass a …

Add `Pipeline` `from_dict` and `to_dict` methods

---

canals/pipeline/pipeline.py
canals/pipeline/validation.py
test/pipelines/unit/test_pipeline.py
test/pipelines/unit/test_validation_pipeline_io.py

As discovered in #67, outputting 0 is equivalent to outputting nothing which shouldn't be the case. The validation also misses when an input is set to 0.
This PR fixes this at two points in the code which fix the issue for me. However, it might also occur somewhere else which I have missed.
I have run the tests manually and they are all passing.

fix: handle falsy node I/O properly

---

canals/errors.py
canals/serialization.py
test/test_serialization.py

Part of #84.
Add generic utility functions to ease serialization and deserialization of Components and other clasess.
They are extremely similar to [`_default_component_to_dict`](https://github.com/deepset-ai/canals/blob/50c1afd1404e11321d58960196fc9231ce94654e/canals/component/component.py#L288) and [`_default_component_from_dict`](https://github.com/deepset-ai/canals/blob/50c1afd1404e11321d58960196fc9231ce94654e/canals/component/component.py#L300C5-L300C33) but with no references to `Component` as they can be used for any class and object.
Example usage:
```
class MyClass:
def __init__(self, my_param: int = 10):
self.my_param = my_param
def to_dict(self):
return default_to_dict(self, my_param=self.my_param)
@classmethod
def from_dict(cls, data):
return default_from_dict(cls, data)
obj = …
```

Implement generic `default_to_dict` and `default_from_dict`

---

canals/pipeline/pipeline.py

Closes #72.
`Component.defaults` is a leftover from a previous implementation to handle default parameters for `Component.run()`. 
Since we handle it in a different way it's not necessary anymore and we safely remove any mention of it.

Remove all mentions of Component.defaults

---

sample_components/concatenate.py
sample_components/double.py
sample_components/parity.py
sample_components/subtract.py
test/sample_components/test_concatenate.py
test/sample_components/test_double.py
test/sample_components/test_parity.py
test/sample_components/test_subtract.py

Depends on #85.
Add `to_dict` and `from_dict` for those Components that didn't have it.

Add to_dict and from_dict for Parity, Subtract, Double, Concatenate

---

canals/pipeline/draw/mermaid.py

`_to_mermaid_text` relies on a `Component` instance having an `init_parameters` field to correctly generate the Mermaid text to draw a `Pipeline`.
Since we remove the setting of `init_parameters` from `@component` that's not going to be reliable anymore. We can instead rely on `Component.to_dict()` to get a representation of the `init_parameters`.
I found out about this issue from PR #88 checks failing.
https://github.com/deepset-ai/canals/actions/runs/5901611206/job/16008083697?pr=88

Change _to_mermaid_text to use component serialization data

---

test/pipelines/unit/test_connections.py
test/test_utils.py

Rename some test classes to suppress `pytest` warnings.
Example warning:
```
============================================================== warnings summary ===============================================================
test/test_utils.py:22
/Users/silvanocerza/workspace/canals/test/test_utils.py:22: PytestCollectionWarning: cannot collect test class 'TestEnum' because it has a __new__ constructor (from: test/test_utils.py)
class TestEnum(Enum):
test/pipelines/unit/test_connections.py:29
/Users/silvanocerza/workspace/canals/test/pipelines/unit/test_connections.py:29: PytestCollectionWarning: cannot collect test class 'TestEnum' because it has a __new__ constructor (from: test/pipelines/unit/test_connections.py)
class TestEnum(Enum):
```

Rename some classes in tests to suppress Pytest warnings

---

canals/component/component.py
test/component/test_component.py

This reverts commit 4529874b562d12331ee2f4fde926ef5b5e3d24d7.
This is probably not as necessary as we thought so we're reverting.
This was thought necessary to better handle serialization of multiple `Pipeline`s but since we removed that it's not necessary anymore.
Also we already have `FileExtensionClassifier` on Haystack that can have output sockets with `/` and `-` since they're named after mime types. e.g. `["text/plain", "audio/x-wav", "image/jpeg"]`

Revert "Check Component I/O socket names are valid (#100)"

---

canals/component/component.py

Duplicate components registration may happen often in Jupyter notebooks and it's harmless in most situations.
This PR downgrades the relative ERROR log to a DEBUG one.

Downgrade log from ERROR to DEBUG

---

canals/component/component.py
canals/errors.py
canals/pipeline/draw/mermaid.py
canals/pipeline/pipeline.py
canals/serialization.py
pyproject.toml
sample_components/greet.py
test/sample_components/test_greet.py

Writing small custom components is very common in teaching material (tutorials, presentations) and might become even more popular depending how the users will receive the new Pipelines in 2.x. Problem is, having to write a `to_dict` and `from_dict` every time is cumbersome, even if the implementation is a single line thanks to the default methods provided by canals.
The idea is to remove `to_dict` and `from_dict` from the Component protocol and make them optional. We use the default serialization methods we already have when `to_dict` or `from_dict` are not present in a component class.
Caveat: when `to_dict` is not present, we inspect the `__init__` signature and see if the init parameters were assigned to an instance variable. If that wasn't the case, we resort to the default value of …

Make to/from_dict optional

---

canals/pipeline/pipeline.py
test/pipelines/unit/test_pipeline.py

Makes sure that the component's output is a dictionary and raises a meaningful error if it isn't.

feat: check returned dictionary

---

canals/serialization.py
sample_components/add_value.py
sample_components/concatenate.py
sample_components/double.py
sample_components/parity.py
sample_components/remainder.py
sample_components/repeat.py
sample_components/subtract.py
sample_components/sum.py
sample_components/threshold.py
test/sample_components/test_add_value.py
test/sample_components/test_concatenate.py
test/sample_components/test_double.py
test/sample_components/test_parity.py
test/sample_components/test_remainder.py
test/sample_components/test_repeat.py
test/sample_components/test_subtract.py
test/sample_components/test_sum.py
test/sample_components/test_threshold.py

I introduced a bug in #107: when you don't provide an `__init__` method, Python provides a default constructor with the signature `__init__(self, *args, **kwargs)`. This caused `inspect` to return `dict_items([('args', <Parameter "*args">), ('kwargs', <Parameter "**kwargs">)])` causing canals to complain with `canals.errors.SerializationError: Cannot determined the value of the init parameter 'args'...`.
The fix just ignores `args` and `kwargs` during the inspection. This would break if an user has a custom components with something like `def __init__(self, args: str = "my args")` but I'd argue such a user deserves a long debugging session as a punishment.
In this same PR (let me know if you want it separated):
- Remove trivial serialization methods from sample components
- Adjusted the …

fix default serialization and adjust sample components accordingly

---

canals/pipeline/draw/draw.py
canals/pipeline/draw/mermaid.py
canals/pipeline/pipeline.py
test/pipelines/unit/test_draw.py

We recently discovered that many Haystack components break the draw function due to the complexity of their init parameters. 
- Replaces a deepcopy step that was breaking PromptBuilder with a shallower copy (see comments)
- Removes the drawing of optional inputs, replaced with a better representation within the component's box.
- Remove the init parameters from the diagram
- Renames `mermaid-img` to `mermaid-image` to be consistent with `mermaid-text`
- Fixes tests
- Local unit tests
- Tested on Haystack RAG pipelines successfully
Example RAG:

fix: `draw` function vs init parameters

---

canals/pipeline/pipeline.py

- fixes #130 
- Getting sender and receiver edge names separately from graph_edges rather than splitting by "/"
Manual tests with end-to-end test in Haystack https://github.com/deepset-ai/haystack/pull/6037
I didn't hash the edge keys in this PR because the edge keys values are heavily used in the tests in test/pipeline/unit/test_connections.py

fix: Sockets named "text/plain" or containing a "/" fail during pipeline.to_dict

---

docs/api-docs/component.md

Adds back a reference to the `components.sockets` module for PyDoc to generate the API Documentation for it.

chore: add sockets docs

---

canals/component/component.py
canals/pipeline/pipeline.py
test/component/test_component.py
test/pipeline/integration/test_complex_pipeline.py
test/pipeline/integration/test_fixed_merging_pipeline.py
test/pipeline/integration/test_variable_merging_pipeline.py

Simplify code and remove side effects from sharing a mutable container.

Do not use a dict as intermediate format and use `Socket`s directly

---

canals/component/component.py
canals/component/sockets.py
test/component/test_component.py
test/component/test_sockets.py
test/pipeline/unit/test_pipeline.py
test/pipeline/unit/test_validation_pipeline_io.py

The dataclass can take care of determining the type, let's make the caller code less verbose

Move `is_optional` evaluation for `InputSocket` to `post_init`

---

canals/__init__.py
canals/pipeline/pipeline.py

Annotate the return type of `classmethods` with a generic type bounded to `canals.Pipeline`. This way, when derived classes need to return `cls` (e.g. other classmethods) mypy will understand what's going on.

Properly annotate classmethods

---

pyproject.toml

`typing_extensions` is used but is missing from dependencies, both explicit and transient.
Error:
```
>>> from canals import component
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/silvanocerza/workspace/canals/canals/__init__.py", line 6, in <module>
from canals.component import component, Component
File "/Users/silvanocerza/workspace/canals/canals/component/__init__.py", line 4, in <module>
from canals.component.component import component, Component
File "/Users/silvanocerza/workspace/canals/canals/component/component.py", line 76, in <module>
from canals.component.sockets import InputSocket, OutputSocket
File "/Users/silvanocerza/workspace/canals/canals/component/sockets.py", line 8, in <module>
from canals.component.types import …
```

Add missing `typing_extensions` dependency

---

canals/component/component.py
canals/component/descriptions.py
test/component/test_component.py

To enable introspection of Canals components, namely the ability to retrieve information about component inputs and outputs programmatically.
Two methods, `component_inputs` and `component_outputs`, were added in `canals/component/descriptions.py`
```
def component_inputs(component: Any) -> Dict[str, Dict[str, Any]]:
...
def component_outputs(component: Any) -> Dict[str, Dict[str, Any]]:
```
Once this PR is merged, Canals component instances could be inspected for inputs/outputs:
```python
from canals import component
from canals.component.descriptions import component_inputs, component_outputs
@component
class MockComponent:
def run(self, value: int):
return {"value": 1}
comp = MockComponent()
assert component_inputs(comp) == {"value": {"is_optional": False, "type": int}}
@component …
```

feat: Add Component inputs/outputs functions

---

canals/component/descriptions.py
test/component/test_component.py

- Fixes premature merge of https://github.com/deepset-ai/canals/pull/158 
- I didn't update the branch and rerun unit tests before the merge
- is_optional field was removed from the canals input socket, causing execution and test failures
- This PR fixes `find_component_inputs` to report on `is_mandatory` and `is_variadic` fields of an input socket

feat: Fix find_component_inputs, update unit tests

---

canals/component/component.py
sample_components/__init__.py
sample_components/fstring.py
test/pipeline/integration/test_dynamic_inputs_pipeline.py
test/sample_components/test_fstring.py

Follow up of https://github.com/deepset-ai/canals/pull/148
---
Currently,  input sockets are read from the `set_input_types` call only, and therefore all count as mandatory. However, one may want to still specify defaults for non-dynamic inputs, such as what PromptBuilder does now:
```python
class PromptBuilder:
def __init__(self, ...):
....
component.set_input_types(self, **dynamic_input_slots)
def run(self, messages: Optional[List[ChatMessage]] = None, **kwargs): 
...
```
This PR makes the signature above work by reading the signature of `run()` even when `__canals_inputs__` already exists, and makes sure to add additional sockets and to check whether they have defaults.
It also adds a sample component showing this signature (`FString`, similar to `PromptBuilder`), unit tests for it, …

feat: read defaults from `run()` signature

---

canals/component/component.py
canals/pipeline/pipeline.py
canals/serialization.py
sample_components/accumulate.py
sample_components/merge_loop.py
test/component/test_component.py
test/pipeline/integration/test_looping_pipeline.py
test/pipeline/unit/test_pipeline.py
test/sample_components/test_accumulate.py
test/sample_components/test_add_value.py
test/sample_components/test_concatenate.py
test/sample_components/test_double.py
test/sample_components/test_greet.py
test/sample_components/test_merge_loop.py
test/sample_components/test_parity.py
test/sample_components/test_remainder.py
test/sample_components/test_repeat.py
test/sample_components/test_subtract.py
test/sample_components/test_sum.py
test/sample_components/test_threshold.py
test/test_serialization.py
test/testing/test_factory.py

fixes: https://github.com/deepset-ai/haystack/issues/6186
- Use full import path of the component as `type` in its dict representation
- Try to import the full path when deserializing a component
Before:
```py
pipeline_dict = {
"components": {
"greeter": {
"type": "Greet",
"init_parameters": {
"message": "\nGreeting component says: Hi! The value is {value}\n",
"log_level": "INFO",
},
}
},
...
}
```
After:
```py
pipeline_dict = {
"components": {
"greeter": {
"type": "sample_components.greet.Greet",  # <-- Now we use the full import path to represent the type
"init_parameters": {
"message": "\nGreeting component says: Hi! The value is {value}\n",
"log_level": "INFO",
},
}
},
...
}
```

Use full import path as 'type' in serialization. 
